export const API_CALL_IN_PROGRESS = 'API_CALL_IN_PROGRESS';
export const API_CALL_HAS_ERROR = 'API_CALL_HAS_ERROR';
export const API_CALL_HAS_SUCCESS = 'API_CALL_HAS_SUCCESS';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
